import os

ASSETS_PATH = os.getcwd() + "/../Assets/"
# ASSETS_PATH = os.getcwd() + "/Assets/"
DATASET_PATH = ASSETS_PATH + "Dataset/"
PICKELS_PATH = DATASET_PATH + "Pickels/"
IMAGES_PATH = DATASET_PATH + "Images/"
MODEL_STRUCTURES_PATH = ASSETS_PATH + "ModelStructures/"
MODEL_PICKELS_FILE = MODEL_STRUCTURES_PATH + "model_pickels.json"
NEURAL_NETWORK_MODEL_PATH = MODEL_STRUCTURES_PATH + "NeuralNetworkModel/"
DECISION_TREE_PATH = MODEL_STRUCTURES_PATH + "DecisionTreeModel/"
DECISION_TREE_MODEL_PATH = DECISION_TREE_PATH + "Model/"
DECISION_TREE_PLOT_PATH = DECISION_TREE_PATH + "TreePlot/"
